# Generated by Django 2.1 on 2018-08-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='createtime',
            new_name='create_time',
        ),
    ]
