# Generated by Django 2.1 on 2018-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
